set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',*:Tc'
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set -g base-index 1

# remap prefix to screens
set -g prefix C-a
bind C-a send-prefix
unbind C-b

# quality of life stuff
set -g history-limit 10000
set -g allow-rename off

# no delay for escape key press
set -sg escape-time 0

# reload tmux config
bind r source-file ~/.tmux.conf

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Join Windows
#bind-key j command-prompt -p "join pane from:" "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:" "join-pane -t '%%'"

# Search Mode VI (default is emacs)
set-window-option -g mode-keys vi

# Vim like pane switching
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# use Alt-vim keys without prefix to switch panes
#bind -n M-h select-pane -L
#bind -n M-j select-pane -D
#bind -n M-k select-pane -U
#bind -n M-l select-pane -R

# switch panes using Alt-arrow without prefix
#bind -n M-Left select-pane -L
#bind -n M-Right select-pane -R
#bind -n M-Up select-pane -U
#bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

#Logging
#run-shell /opt/tmux-logging/logging.tmux

# Theme
set-option -g pane-active-border-style fg=green
set-window-option -g monitor-activity on

set-window-option -g status-fg black
set-window-option -g status-bg green
set-window-option -g status-left '#[fg=black bold, bg=white] #S '
set-window-option -g status-right '#[fg=black, bg=white] %H:%M %d-%b-%y '
set-window-option -g window-status-format "#[fg=black, bg=green] #I: #W "
set-window-option -g window-status-current-format '#[fg=green bold, bg=colour233] #I: #W '

# list of plugins
#set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'tmux-plugins/tmux-resurrect'

# initialize TMUX plugin manager (keep this line at very bottom of .tmux.conf)
#run -b '~/.tmux/plugins/tpm'
